server:
  port: 8082
  servlet:
    context-path: /DM_SB_LogAnalyzer

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
logging:
  level:
    root: INFO
    com.dm.controller: TRACE