server:
  port: 8082
  servlet:
    context-path: /DM_SB_LogAnalyzer

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
openai.api.key: sk-vvszxdWNFFCx43epSAvdBnJxCGDaywooM0RP3OtRt-T3BlbkFJtmzx37bR9TFjG8q7DbLe0fvpR6vf_hILZRDAwdwCcA
openai.api.keyShivam: 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
golu.sec: AIzaSyDrYXj-ZWdtuNQN424ATOpC_mwTHxJn9nc
golu.Url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent

logging:
  level:
    root: INFO
    com.dm.controller: TRACE